<?php /** @noinspection PhpUnused */

declare(strict_types=1);

namespace HomeeApi\CA;

class CAAttributeType extends CA
{
    public const CAAttributeTypeNone = 0;
    public const CAAttributeTypeOnOff = 1;
    public const CAAttributeTypeDimmingLevel = 2;
    public const CAAttributeTypeCurrentEnergyUse = 3;
    public const CAAttributeTypeAccumulatedEnergyUse = 4;
    public const CAAttributeTypeTemperature = 5;
    public const CAAttributeTypeTargetTemperature = 6;
    public const CAAttributeTypeRelativeHumidity = 7;
    public const CAAttributeTypeBatteryLevel = 8;
    public const CAAttributeTypeStatusLED = 9;
    public const CAAttributeTypeWindowPosition = 10;
    public const CAAttributeTypeBrightness = 11;
    public const CAAttributeTypeFloodAlarm = 12;
    public const CAAttributeTypeSiren = 13;
    public const CAAttributeTypeOpenClose = 14;
    public const CAAttributeTypePosition = 15;
    public const CAAttributeTypeSmokeAlarm = 16;
    public const CAAttributeTypeBlackoutAlarm = 17;
    public const CAAttributeTypeCurrentValvePosition = 18;
    public const CAAttributeTypeBinaryInput = 19;
    public const CAAttributeTypeCO2Level = 20;
    public const CAAttributeTypePressure = 21;
    public const CAAttributeTypeLevel = 22;
    public const CAAttributeTypeColor = 23;
    public const CAAttributeTypeSaturation = 24;
    public const CAAttributeTypeMotionAlarm = 25;
    public const CAAttributeTypeMotionSensitivity = 26;
    public const CAAttributeTypeMotionInsensitivity = 27;
    public const CAAttributeTypeMotionAlarmCancelationDelay = 28;
    public const CAAttributeTypeWakeUpInterval = 29;
    public const CAAttributeTypeTamperAlarm = 30;
    public const CAAttributeTypeWarmWaterTemperature = 31;
    public const CAAttributeTypeWarmWaterTargetTemperature = 32;
    public const CAAttributeTypeLinkQuality = 33;
    public const CAAttributeTypeInovaAlarmSystemState = 34;
    public const CAAttributeTypeInovaAlarmGroupState = 35;
    public const CAAttributeTypeInovaAlarmIntrusionState = 36;
    public const CAAttributeTypeInovaAlarmErrorState = 37;
    public const CAAttributeTypeInovaAlarmDoorState = 38;
    public const CAAttributeTypeInovaAlarmExternalSensor = 39;
    public const CAAttributeTypeButtonState = 40;
    public const CAAttributeTypeHue = 41;
    public const CAAttributeTypeColorTemperature = 42;
    public const CAAttributeTypeHardwareRevision = 43;
    public const CAAttributeTypeFirmwareRevision = 44;
    public const CAAttributeTypeSoftwareRevision = 45;
    public const CAAttributeTypeLEDState = 46;
    public const CAAttributeTypeLEDStateWhenOn = 47;
    public const CAAttributeTypeLEDStateWhenOff = 48;
    public const CAAttributeTypeTargetTemperatureOffset = 49;
    public const CAAttributeTypeSavingFactor = 50;
    public const CAAttributeTypeTotalVoltage = 51;
    public const CAAttributeTypeHighTemperatureAlarm = 52;
    public const CAAttributeTypeHighTemperatureAlarmTreshold = 53;
    public const CAAttributeTypeLowTemperatureAlarm = 54;
    public const CAAttributeTypeLowTemperatureAlarmTreshold = 55;
    public const CAAttributeTypeTamperSensitivity = 56;
    public const CAAttributeTypeTamperAlarmCancelationDelay = 57;
    public const CAAttributeTypeBrightnessReportInterval = 58;
    public const CAAttributeTypeTemperatureReportInterval = 59;
    public const CAAttributeTypeMotionAlarmIndicationMode = 60;
    public const CAAttributeTypeLEDBrightness = 61;
    public const CAAttributeTypeTamperAlarmIndicationMode = 62;
    public const CAAttributeTypeSwitchType = 63;
    public const CAAttributeTypeTemperatureOffset = 64;
    public const CAAttributeTypeAccumulatedWaterUse = 65;
    public const CAAttributeTypeAccumulatedWaterUseLastMonth = 66;
    public const CAAttributeTypeCurrentDate = 67;
    public const CAAttributeTypeLeakAlarm = 68;
    public const CAAttributeTypeBatteryLowAlarm = 69;
    public const CAAttributeTypeMalfunctionAlarm = 70;
    public const CAAttributeTypeLinkQualityAlarm = 71;
    public const CAAttributeTypeMode = 72;
    public const CAAttributeTypeHeatingProgram = 73;
    public const CAAttributeTypeWarmWaterProgram = 74;
    public const CAAttributeTypeCalibration = 75;
    public const CAAttributeTypePresenceAlarm = 76;
    public const CAAttributeTypeMinimumAlarm = 77;
    public const CAAttributeTypeMaximumAlarm = 78;
    public const CAAttributeTypeOilAlarm = 79;
    public const CAAttributeTypeWaterAlarm = 80;
    public const CAAttributeTypeInovaAlarmInhibition = 81;
    public const CAAttributeTypeInovaAlarmEjection = 82;
    public const CAAttributeTypeInovaAlarmCommercialRef = 83;
    public const CAAttributeTypeSerialNumber = 84;
    public const CAAttributeTypeRadiatorThermostatSummerMode = 85;
    public const CAAttributeTypeInovaAlarmOperationMode = 86;
    public const CAAttributeTypeAutomaticMode = 87;
    public const CAAttributeTypePollingInterval = 88;
    public const CAAttributeTypeFeedTemperature = 89;
    public const CAAttributeTypeDisplayOrientation = 90;
    public const CAAttributeTypeManualOperation = 91;
    public const CAAttributeTypeDeviceTemperature = 92;
    public const CAAttributeTypeSonometer = 93;
    public const CAAttributeTypeAirPressure = 94;
    public const CAAttributeTypeOutdoorRelativeHumidity = 95;
    public const CAAttributeTypeIndoorRelativeHumidity = 96;
    public const CAAttributeTypeOutdoorTemperature = 97;
    public const CAAttributeTypeIndoorTemperature = 98;
    public const CAAttributeTypeVentilationLevel = 99;
    public const CAAttributeTypeVentilationMode = 100;
    public const CAAttributeTypeRainFall = 101;
    public const CAAttributeTypeIntakeMotorRevs = 102;
    public const CAAttributeTypeExhaustMotorRevs = 103;
    public const CAAttributeTypeOperatingHours = 104;
    public const CAAttributeTypeInovaAlarmSilentAlert = 105;
    public const CAAttributeTypeInovaAlarmPreAlarm = 106;
    public const CAAttributeTypeInovaAlarmDeterrenceAlarm = 107;
    public const CAAttributeTypeInovaAlarmWarning = 108;
    public const CAAttributeTypeInovaAlarmFireAlarm = 109;
    public const CAAttributeTypeUpTime = 110;
    public const CAAttributeTypeDownTime = 111;
    public const CAAttributeTypeShutterBlindMode = 112;
    public const CAAttributeTypeShutterSlatPosition = 113;
    public const CAAttributeTypeShutterSlatTime = 114;
    public const CAAttributeTypeRestartDevice = 115;
    public const CAAttributeTypeSoilMoisture = 116;
    public const CAAttributeTypeWaterPlantAlarm = 117;
    public const CAAttributeTypeMistPlantAlarm = 118;
    public const CAAttributeTypeFertilizePlantAlarm = 119;
    public const CAAttributeTypeCoolPlantAlarm = 120;
    public const CAAttributeTypeHeatPlantAlarm = 121;
    public const CAAttributeTypePutPlantIntoLightAlarm = 122;
    public const CAAttributeTypePutPlantIntoShadeAlarm = 123;
    public const CAAttributeTypeColorMode = 124;
    public const CAAttributeTypeTargetTemperatureLow = 125;
    public const CAAttributeTypeTargetTemperatureHigh = 126;
    public const CAAttributeTypeHVACMode = 127;
    public const CAAttributeTypeAway = 128;
    public const CAAttributeTypeHVACState = 129;
    public const CAAttributeTypeHasLeaf = 130;
    public const CAAttributeTypeSetEnergyConsumption = 131;
    public const CAAttributeTypeCOAlarm = 132;
    public const CAAttributeTypeRestoreLastKnownState = 133;
    public const CAAttributeTypeLastImageReceived = 134;
    public const CAAttributeTypeUpDown = 135;
    public const CAAttributeTypeRequestVOD = 136;
    public const CAAttributeTypeInovaDetectorHistory = 137;
    public const CAAttributeTypeSurgeAlarm = 138;
    public const CAAttributeTypeLoadAlarm = 139;
    public const CAAttributeTypeOverloadAlarm = 140;
    public const CAAttributeTypeVoltageDropAlarm = 141;
    public const CAAttributeTypeShutterOrientation = 142;
    public const CAAttributeTypeOverCurrentAlarm = 143;
    public const CAAttributeTypeSirenMode = 144;
    public const CAAttributeTypeAlarmAutoStopTime = 145;
    public const CAAttributeTypeWindSpeed = 146;
    public const CAAttributeTypeWindDirection = 147;
    public const CAAttributeTypeComfortTemperature = 148;
    public const CAAttributeTypeEcoTemperature = 149;
    public const CAAttributeTypeReduceTemperature = 150;
    public const CAAttributeTypeProtectTemperature = 151;
    public const CAAttributeTypeInovaSystemTime = 152;
    public const CAAttributeTypeInovaCorrespondentProtocol = 153;
    public const CAAttributeTypeInovaCorrespondentID = 154;
    public const CAAttributeTypeInovaCorrespondentListen = 155;
    public const CAAttributeTypeInovaCorrespondentNumber = 156;
    public const CAAttributeTypeInovaCallCycleFireProtection = 157;
    public const CAAttributeTypeInovaCallCycleIntrusion = 158;
    public const CAAttributeTypeInovaCallCycleTechnicalProtect = 159;
    public const CAAttributeTypeInovaCallCycleFaults = 160;
    public const CAAttributeTypeInovaCallCycleDeterrence = 161;
    public const CAAttributeTypeInovaCallCyclePrealarm = 162;
    public const CAAttributeTypeInovaPSTNRings = 163;
    public const CAAttributeTypeInovaDoubleCallRings = 164;
    public const CAAttributeTypeInovaPIN = 165;
    public const CAAttributeTypeInovaPUK = 166;
    public const CAAttributeTypeInovaMainMediaSelection = 167;
    public const CAAttributeTypeRainFallLastHour = 168;
    public const CAAttributeTypeRainFallToday = 169;
    public const CAAttributeTypeIdentificationMode = 170;
    public const CAAttributeTypeButtonDoubleClick = 171;
    public const CAAttributeTypeSirenTriggerMode = 172;
    public const CAAttributeTypeUV = 173;
    public const CAAttributeTypeSlatSteps = 174;
    public const CAAttributeTypeEcoModeConfig = 175;
    public const CAAttributeTypeButtonLongRelease = 176;
    public const CAAttributeTypeVisualGong = 177;
    public const CAAttributeTypeAcousticGong = 178;
    public const CAAttributeTypeSurveillanceOnOff = 179;
    public const CAAttributeTypeStorageAlarm = 181;
    public const CAAttributeTypePowerSupplyAlarm = 182;
    public const CAAttributeTypeNetatmoHome = 183;
    public const CAAttributeTypeNetatmoPerson = 184;
    public const CAAttributeTypeNetatmoLastEventPersonId = 185;
    public const CAAttributeTypeNetatmoLastEventTime = 186;
    public const CAAttributeTypeNetatmoLastEventType = 187;
    public const CAAttributeTypeNetatmoLastEventIsKnownPerson = 188;
    public const CAAttributeTypeNetatmoLastEventIsArrival = 189;
    public const CAAttributeTypePresenceTimeout = 190;
    public const CAAttributeTypeKnownPersonPresence = 191;
    public const CAAttributeTypeUnknownPersonPresence = 192;
    public const CAAttributeTypeCurrent = 193;
    public const CAAttributeTypeFrequency = 194;
    public const CAAttributeTypeVoltage = 195;
    public const CAAttributeTypePresenceAlarmCancelationDelay = 196;
    public const CAAttributeTypePresenceAlarmDetectionDelay = 197;
    public const CAAttributeTypePresenceAlarmThreshold = 198;
    public const CAAttributeTypeNetatmoThermostatMode = 199;
    public const CAAttributeTypeNetatmoRelayBoilerConnected = 200;
    public const CAAttributeTypeNetatmoRelayMac = 201;
    public const CAAttributeTypeNetatmoThermostatModeTimeout = 202;
    public const CAAttributeTypeNetatmoThermostatNextChange = 203;
    public const CAAttributeTypeNetatmoThermostatPrograms = 204;
    public const CAAttributeTypeHomeeMode = 205;
    public const CAAttributeTypeColorWhite = 206;
    public const CAAttributeTypeMovementAlarm = 207;
    public const CAAttributeTypeMovementSensitivity = 208;
    public const CAAttributeTypeVibrationAlarm = 209;
    public const CAAttributeTypeVibrationSensitivity = 210;
    public const CAAttributeTypeAverageEnergyUse = 211;
    public const CAAttributeTypeBinaryInputMode = 212;
    public const CAAttributeTypeDeviceStatus = 213;
    public const CAAttributeTypeDeviceRemainingTime = 214;
    public const CAAttributeTypeDeviceStartTime = 215;
    public const CAAttributeTypeDeviceProgram = 216;
    public const CAAttributeTypeMultilevelInput = 222;
    public const CAAttributeTypeButtonPressed3Times = 223;
    public const CAAttributeTypeButtonPressed4Times = 224;
    public const CAAttributeTypeButtonPressed5Times = 225;
    public const CAAttributeTypeRepeaterMode = 226;
    public const CAAttributeTypeAutoOffTime = 227;
    public const CAAttributeTypeCO2Alarm = 228;
    public const CAAttributeTypeInputEndpointConfiguration = 229;
    public const CAAttributeTypeGustSpeed = 230;
    public const CAAttributeTypeGustDirection = 231;
    public const CAAttributeTypeLockState = 232;
    public const CAAttributeTypeAeotecSmartPlugLEDState = 233;
    public const CAAttributeTypeAlarmDuration = 234;
    public const CAAttributeTypeDewPoint = 235;
    public const CAAttributeTypeGesture = 236;
    public const CAAttributeTypeGestureSequenceLearningMode = 237;
    public const CAAttributeTypeGestureSequence = 238;
    public const CAAttributeTypeTotalCurrentEnergyUse = 239;
    public const CAAttributeTypeTotalAccumulatedEnergyUse = 240;
    public const CAAttributeTypeSunsetTime = 241;
    public const CAAttributeTypeSunriseTime = 242;
    public const CAAttributeTypeCurrentLocalWeatherCondition = 243;
    public const CAAttributeTypeCurrentLocalTemperature = 244;
    public const CAAttributeTypeCurrentLocalHumidity = 245;
    public const CAAttributeTypeForecastLocalWeatherCondition = 246;
    public const CAAttributeTypeForecastLocalTempMin = 247;
    public const CAAttributeTypeForecastLocalTempMax = 248;
    public const CAAttributeTypeArmed = 249;
    public const CAAttributeTypeFloodlight = 250;
    public const CAAttributeTypeHumanDetected = 251;
    public const CAAttributeTypeVehicleDetected = 252;
    public const CAAttributeTypeAnimalDetected = 253;
    public const CAAttributeTypeVacationMode = 254;
    public const CAAttributeTypeBlinkInterval = 255;
    public const CAAttributeTypeOtherMotionDetected = 256;
    public const CAAttributeTypeIRCodeNumber = 257;
    public const CAAttributeTypeHeatingMode = 258;
    public const CAAttributeTypeDisplayAutoOffTime = 259;
    public const CAAttributeTypeBacklight = 260;
    public const CAAttributeTypeOpenWindowDetectionSensibility = 261;
    public const CAAttributeTypeCurrentLocalWindSpeed = 262;
    public const CAAttributeTypeCurrentLocalGustSpeed = 263;
    public const CAAttributeTypePowerOutputGrid = 264;
    public const CAAttributeTypePowerInputGrid = 265;
    public const CAAttributeTypePowerPV = 266;
    public const CAAttributeTypePowerLoad = 267;
    public const CAAttributeTypePowerOutputBattery = 268;
    public const CAAttributeTypePowerInputBattery = 269;
    public const CAAttributeTypeRelativeAutonomy = 270;
    public const CAAttributeTypeRelativeSelfConsumption = 271;
    public const CAAttributeTypeTotalCurrent = 272;
    public const CAAttributeTypeEnergyStorageLevel = 273;
    public const CAAttributeTypeTotalEnergyLoad = 274;
    public const CAAttributeTypeTotalEnergyProduction = 275;
    public const CAAttributeTypeTotalEnergyOutputGrid = 276;
    public const CAAttributeTypeTotalEnergyInputGrid = 277;
    public const CAAttributeTypeTotalEnergyStored = 278;
    public const CAAttributeTypeTotalEnergyRestored = 279;
    public const CAAttributeTypeReplaceFilterAlarm = 289;
    public const CAAttributeTypeUnknownNotification = 291;
    public const CAAttributeTypeRFProtection = 297;
    public const CAAttributeTypeExpertMode = 299;
    public const CAAttributeTypeUpDownRemote = 300;
    public const CAAttributeTypeDawn = 301;
    public const CAAttributeTypeRainfallIntensity = 302;
    public const CAAttributeTypeImpulse = 304;
    public const CAAttributeTypeLightImpulse = 305;
    public const CAAttributeTypeOpenPartialImpulse = 306;
    public const CAAttributeTypeExternalBinaryInput = 309;
    public const CAAttributeTypeButtonPressedLong = 310;
    public const CAAttributeTypeMemoryUsage = 311;
    public const CAAttributeTypeProcessorUtilization = 312;
    public const CAAttributeTypeUsedStorage = 313;
    public const CAAttributeTypeExternalTemperature = 315;
    public const CAAttributeTypeFloorTemperature = 316;
    public const CAAttributeTypeCurrentElectricityPrice = 317;
    public const CAAttributeTypeHighestElectricityPrice = 318;
    public const CAAttributeTypeLowestElectricityPrice = 319;
    public const CAAttributeTypeCurrentEnergyConsumption = 320;
    public const CAAttributeTypeCurrentCosts = 321;
    public const CAAttributeTypeSlatMinAngle = 322;
    public const CAAttributeTypeSlatMaxAngle = 323;
    public const CAAttributeTypeMotorRotation = 324;
    public const CAAttributeTypeEndPositionConfiguration = 325;
    public const CAAttributeTypeAutomaticModeImpulse = 326;
    public const CAAttributeTypeBrieflyOpenImpulse = 327;
    public const CAAttributeTypePermanentlyOpenImpulse = 328;
    public const CAAttributeTypeWindThreshold = 329;
    public const CAAttributeTypeMotorBlockedAlarm = 330;
    public const CAAttributeTypeFreezeProtection = 331;
    public const CAAttributeTypeFlyScreen = 332;
    public const CAAttributeTypeSunProtection = 333;
    public const CAAttributeTypeMemo = 334;
    public const CAAttributeTypeSlatRotationImpulse = 337;
    public const CAAttributeWindMonitoringState = 338;
    public const CAAttributeTypeHVACOperatingState = 339;
    public const CAAttributeTypeExternalTemperatureOffset = 340;
    public const CAAttributeTypeFloorTemperatureOffset = 341;
    public const CAAttributeTypeDisplayBrightnessActive = 342;
    public const CAAttributeTypeDisplayBrightnessDimmed = 343;
    public const CAAttributeTypeButtonBrightnessActive = 344;
    public const CAAttributeTypeButtonBrightnessDimmed = 345;
    public const CAAttributeTypeDisplayTemperatureSelection = 346;
    public const CAAttributeTypeResetMeter = 347;
    public const CAAttributeTypeAutomaticRuntimeCalculation = 348;
    public const CAAttributeTypeDownPosition = 349;
    public const CAAttributeTypeDownSlatPosition = 350;
    public const CAAttributeTypeFirmwareUpdateable = 351;
    public const CAAttributeTypeCOValue = 354;
    public const CAAttributeTypeTargetTemperatureType = 355;
    public const CAAttributeTypeSetBackMode = 356;
    public const CAAttributeTypeSystemAlarm = 357;
    public const CAAttributeTypeHealthAlarm = 358;
    public const CAAttributeTypeAccessControlAlarm = 359;
    public const CAAttributeTypeSecurityAlarm = 360;
    public const CAAttributeTypeEmergencyAlarm = 361;
    public const CAAttributeTypeClockAlarm = 362;
    public const CAAttributeTypeApplianceAlarm = 363;
    public const CAAttributeTypeWaterValveAlarm = 364;
    public const CAAttributeTypeWeatherAlarm = 365;
    public const CAAttributeTypeIrrigationAlarm = 366;
    public const CAAttributeTypeGasAlarm = 367;
    public const CAAttributeTypePestAlarm = 368;
    public const CAAttributeTypeLightAlarm = 369;
    public const CAAttributeTypeWaterQualityAlarm = 370;
    public const CAAttributeTypeAntiTheftRestricted = 371;
    public const CAAttributeTypeUnknownMeteringValue = 372;
    public const CAAttributeTypeColorExpert = 373;
    public const CAAttributeTypeSwitchMultilevelExpert = 375;
    public const CAAttributeTypeUnknownSensorValue = 376;
    public const CAAttributeTypeDoorLockExpert = 377;
    public const CAAttributeTypeVOCLevel = 352;
    public const CAAttributeTypeVOCValue = 353;
    public const CAAttributeTypeVentilateImpulse = 378;
    public const CAAttributeTypeVibrationOnOff = 379;
    public const CAAttributeTypeSoundOnOff = 380;
    public const CAAttributeTypeVirtualVolantPostion = 381;
    public const CAAttributeTypeFabricUntensioning = 382;
    public const CAAttributeTypeAutomaticReversing = 383;
    public const CAAttributeTypeLocked = 384;
    public const CAAttributeTypeWatchdogOnOff = 385;
    public const CAAttributeTypeIPAddress = 386;
    public const CAAttributeTypeGasAlarmState = 387;
    public const CAAttributeTypeGasConcentration = 388;
    public const CAAttributeTypeHostname = 389;
    public const CAAttributeTypeBrightnessLevel = 390;
    public const CAAttributeTypeForecastLocalHumidity = 391;
    public const CAAttributeTypeForecastLocalWindSpeed = 392;
    public const CAAttributeTypeForecastLocalGustSpeed = 393;

    protected static array $mapping = [
        0 => 'None',
        1 => 'OnOff',
        2 => 'DimmingLevel',
        3 => 'CurrentEnergyUse',
        4 => 'AccumulatedEnergyUse',
        5 => 'Temperature',
        6 => 'TargetTemperature',
        7 => 'RelativeHumidity',
        8 => 'BatteryLevel',
        9 => 'StatusLED',
        10 => 'WindowPosition',
        11 => 'Brightness',
        12 => 'FloodAlarm',
        13 => 'Siren',
        14 => 'OpenClose',
        15 => 'Position',
        16 => 'SmokeAlarm',
        17 => 'BlackoutAlarm',
        18 => 'CurrentValvePosition',
        19 => 'BinaryInput',
        20 => 'CO2Level',
        21 => 'Pressure',
        22 => 'Level',
        23 => 'Color',
        24 => 'Saturation',
        25 => 'MotionAlarm',
        26 => 'MotionSensitivity',
        27 => 'MotionInsensitivity',
        28 => 'MotionAlarmCancelationDelay',
        29 => 'WakeUpInterval',
        30 => 'TamperAlarm',
        31 => 'WarmWaterTemperature',
        32 => 'WarmWaterTargetTemperature',
        33 => 'LinkQuality',
        34 => 'InovaAlarmSystemState',
        35 => 'InovaAlarmGroupState',
        36 => 'InovaAlarmIntrusionState',
        37 => 'InovaAlarmErrorState',
        38 => 'InovaAlarmDoorState',
        39 => 'InovaAlarmExternalSensor',
        40 => 'ButtonState',
        41 => 'Hue',
        42 => 'ColorTemperature',
        43 => 'HardwareRevision',
        44 => 'FirmwareRevision',
        45 => 'SoftwareRevision',
        46 => 'LEDState',
        47 => 'LEDStateWhenOn',
        48 => 'LEDStateWhenOff',
        49 => 'TargetTemperatureOffset',
        50 => 'SavingFactor',
        51 => 'TotalVoltage',
        52 => 'HighTemperatureAlarm',
        53 => 'HighTemperatureAlarmTreshold',
        54 => 'LowTemperatureAlarm',
        55 => 'LowTemperatureAlarmTreshold',
        56 => 'TamperSensitivity',
        57 => 'TamperAlarmCancelationDelay',
        58 => 'BrightnessReportInterval',
        59 => 'TemperatureReportInterval',
        60 => 'MotionAlarmIndicationMode',
        61 => 'LEDBrightness',
        62 => 'TamperAlarmIndicationMode',
        63 => 'SwitchType',
        64 => 'TemperatureOffset',
        65 => 'AccumulatedWaterUse',
        66 => 'AccumulatedWaterUseLastMonth',
        67 => 'CurrentDate',
        68 => 'LeakAlarm',
        69 => 'BatteryLowAlarm',
        70 => 'MalfunctionAlarm',
        71 => 'LinkQualityAlarm',
        72 => 'Mode',
        73 => 'HeatingProgram',
        74 => 'WarmWaterProgram',
        75 => 'Calibration',
        76 => 'PresenceAlarm',
        77 => 'MinimumAlarm',
        78 => 'MaximumAlarm',
        79 => 'OilAlarm',
        80 => 'WaterAlarm',
        81 => 'InovaAlarmInhibition',
        82 => 'InovaAlarmEjection',
        83 => 'InovaAlarmCommercialRef',
        84 => 'SerialNumber',
        85 => 'RadiatorThermostatSummerMode',
        86 => 'InovaAlarmOperationMode',
        87 => 'AutomaticMode',
        88 => 'PollingInterval',
        89 => 'FeedTemperature',
        90 => 'DisplayOrientation',
        91 => 'ManualOperation',
        92 => 'DeviceTemperature',
        93 => 'Sonometer',
        94 => 'AirPressure',
        95 => 'OutdoorRelativeHumidity',
        96 => 'IndoorRelativeHumidity',
        97 => 'OutdoorTemperature',
        98 => 'IndoorTemperature',
        99 => 'VentilationLevel',
        100 => 'VentilationMode',
        101 => 'RainFall',
        102 => 'IntakeMotorRevs',
        103 => 'ExhaustMotorRevs',
        104 => 'OperatingHours',
        105 => 'InovaAlarmSilentAlert',
        106 => 'InovaAlarmPreAlarm',
        107 => 'InovaAlarmDeterrenceAlarm',
        108 => 'InovaAlarmWarning',
        109 => 'InovaAlarmFireAlarm',
        110 => 'UpTime',
        111 => 'DownTime',
        112 => 'ShutterBlindMode',
        113 => 'ShutterSlatPosition',
        114 => 'ShutterSlatTime',
        115 => 'RestartDevice',
        116 => 'SoilMoisture',
        117 => 'WaterPlantAlarm',
        118 => 'MistPlantAlarm',
        119 => 'FertilizePlantAlarm',
        120 => 'CoolPlantAlarm',
        121 => 'HeatPlantAlarm',
        122 => 'PutPlantIntoLightAlarm',
        123 => 'PutPlantIntoShadeAlarm',
        124 => 'ColorMode',
        125 => 'TargetTemperatureLow',
        126 => 'TargetTemperatureHigh',
        127 => 'HVACMode',
        128 => 'Away',
        129 => 'HVACState',
        130 => 'HasLeaf',
        131 => 'SetEnergyConsumption',
        132 => 'COAlarm',
        133 => 'RestoreLastKnownState',
        134 => 'LastImageReceived',
        135 => 'UpDown',
        136 => 'RequestVOD',
        137 => 'InovaDetectorHistory',
        138 => 'SurgeAlarm',
        139 => 'LoadAlarm',
        140 => 'OverloadAlarm',
        141 => 'VoltageDropAlarm',
        142 => 'ShutterOrientation',
        143 => 'OverCurrentAlarm',
        144 => 'SirenMode',
        145 => 'AlarmAutoStopTime',
        146 => 'WindSpeed',
        147 => 'WindDirection',
        148 => 'ComfortTemperature',
        149 => 'EcoTemperature',
        150 => 'ReduceTemperature',
        151 => 'ProtectTemperature',
        152 => 'InovaSystemTime',
        153 => 'InovaCorrespondentProtocol',
        154 => 'InovaCorrespondentID',
        155 => 'InovaCorrespondentListen',
        156 => 'InovaCorrespondentNumber',
        157 => 'InovaCallCycleFireProtection',
        158 => 'InovaCallCycleIntrusion',
        159 => 'InovaCallCycleTechnicalProtect',
        160 => 'InovaCallCycleFaults',
        161 => 'InovaCallCycleDeterrence',
        162 => 'InovaCallCyclePrealarm',
        163 => 'InovaPSTNRings',
        164 => 'InovaDoubleCallRings',
        165 => 'InovaPIN',
        166 => 'InovaPUK',
        167 => 'InovaMainMediaSelection',
        168 => 'RainFallLastHour',
        169 => 'RainFallToday',
        170 => 'IdentificationMode',
        171 => 'ButtonDoubleClick',
        172 => 'SirenTriggerMode',
        173 => 'UV',
        174 => 'SlatSteps',
        175 => 'EcoModeConfig',
        176 => 'ButtonLongRelease',
        177 => 'VisualGong',
        178 => 'AcousticGong',
        179 => 'SurveillanceOnOff',
        181 => 'StorageAlarm',
        182 => 'PowerSupplyAlarm',
        183 => 'NetatmoHome',
        184 => 'NetatmoPerson',
        185 => 'NetatmoLastEventPersonId',
        186 => 'NetatmoLastEventTime',
        187 => 'NetatmoLastEventType',
        188 => 'NetatmoLastEventIsKnownPerson',
        189 => 'NetatmoLastEventIsArrival',
        190 => 'PresenceTimeout',
        191 => 'KnownPersonPresence',
        192 => 'UnknownPersonPresence',
        193 => 'Current',
        194 => 'Frequency',
        195 => 'Voltage',
        196 => 'PresenceAlarmCancelationDelay',
        197 => 'PresenceAlarmDetectionDelay',
        198 => 'PresenceAlarmThreshold',
        199 => 'NetatmoThermostatMode',
        200 => 'NetatmoRelayBoilerConnected',
        201 => 'NetatmoRelayMac',
        202 => 'NetatmoThermostatModeTimeout',
        203 => 'NetatmoThermostatNextChange',
        204 => 'NetatmoThermostatPrograms',
        205 => 'HomeeMode',
        206 => 'ColorWhite',
        207 => 'MovementAlarm',
        208 => 'MovementSensitivity',
        209 => 'VibrationAlarm',
        210 => 'VibrationSensitivity',
        211 => 'AverageEnergyUse',
        212 => 'BinaryInputMode',
        213 => 'DeviceStatus',
        214 => 'DeviceRemainingTime',
        215 => 'DeviceStartTime',
        216 => 'DeviceProgram',
        222 => 'MultilevelInput',
        223 => 'ButtonPressed3Times',
        224 => 'ButtonPressed4Times',
        225 => 'ButtonPressed5Times',
        226 => 'RepeaterMode',
        227 => 'AutoOffTime',
        228 => 'CO2Alarm',
        229 => 'InputEndpointConfiguration',
        230 => 'GustSpeed',
        231 => 'GustDirection',
        232 => 'LockState',
        233 => 'AeotecSmartPlugLEDState',
        234 => 'AlarmDuration',
        235 => 'DewPoint',
        236 => 'Gesture',
        237 => 'GestureSequenceLearningMode',
        238 => 'GestureSequence',
        239 => 'TotalCurrentEnergyUse',
        240 => 'TotalAccumulatedEnergyUse',
        241 => 'SunsetTime',
        242 => 'SunriseTime',
        243 => 'CurrentLocalWeatherCondition',
        244 => 'CurrentLocalTemperature',
        245 => 'CurrentLocalHumidity',
        246 => 'ForecastLocalWeatherCondition',
        247 => 'ForecastLocalTempMin',
        248 => 'ForecastLocalTempMax',
        249 => 'Armed',
        250 => 'Floodlight',
        251 => 'HumanDetected',
        252 => 'VehicleDetected',
        253 => 'AnimalDetected',
        254 => 'VacationMode',
        255 => 'BlinkInterval',
        256 => 'OtherMotionDetected',
        257 => 'IRCodeNumber',
        258 => 'HeatingMode',
        259 => 'DisplayAutoOffTime',
        260 => 'Backlight',
        261 => 'OpenWindowDetectionSensibility',
        262 => 'CurrentLocalWindSpeed',
        263 => 'CurrentLocalGustSpeed',
        264 => 'PowerOutputGrid',
        265 => 'PowerInputGrid',
        266 => 'PowerPV',
        267 => 'PowerLoad',
        268 => 'PowerOutputBattery',
        269 => 'PowerInputBattery',
        270 => 'RelativeAutonomy',
        271 => 'RelativeSelfConsumption',
        272 => 'TotalCurrent',
        273 => 'EnergyStorageLevel',
        274 => 'TotalEnergyLoad',
        275 => 'TotalEnergyProduction',
        276 => 'TotalEnergyOutputGrid',
        277 => 'TotalEnergyInputGrid',
        278 => 'TotalEnergyStored',
        279 => 'TotalEnergyRestored',
        289 => 'ReplaceFilterAlarm',
        291 => 'UnknownNotification',
        297 => 'RFProtection',
        299 => 'ExpertMode',
        300 => 'UpDownRemote',
        301 => 'Dawn',
        302 => 'RainfallIntensity',
        304 => 'Impulse',
        305 => 'LightImpulse',
        306 => 'OpenPartialImpulse',
        309 => 'ExternalBinaryInput',
        310 => 'ButtonPressedLong',
        311 => 'MemoryUsage',
        312 => 'ProcessorUtilization',
        313 => 'UsedStorage',
        315 => 'ExternalTemperature',
        316 => 'FloorTemperature',
        317 => 'CurrentElectricityPrice',
        318 => 'HighestElectricityPrice',
        319 => 'LowestElectricityPrice',
        320 => 'CurrentEnergyConsumption',
        321 => 'CurrentCosts',
        322 => 'SlatMinAngle',
        323 => 'SlatMaxAngle',
        324 => 'MotorRotation',
        325 => 'EndPositionConfiguration',
        326 => 'AutomaticModeImpulse',
        327 => 'BrieflyOpenImpulse',
        328 => 'PermanentlyOpenImpulse',
        329 => 'WindThreshold',
        330 => 'MotorBlockedAlarm',
        331 => 'FreezeProtection',
        332 => 'FlyScreen',
        333 => 'SunProtection',
        334 => 'Memo',
        337 => 'SlatRotationImpulse',
        338 => 'MonitoringState',
        339 => 'HVACOperatingState',
        340 => 'ExternalTemperatureOffset',
        341 => 'FloorTemperatureOffset',
        342 => 'DisplayBrightnessActive',
        343 => 'DisplayBrightnessDimmed',
        344 => 'ButtonBrightnessActive',
        345 => 'ButtonBrightnessDimmed',
        346 => 'DisplayTemperatureSelection',
        347 => 'ResetMeter',
        348 => 'AutomaticRuntimeCalculation',
        349 => 'DownPosition',
        350 => 'DownSlatPosition',
        351 => 'FirmwareUpdateable',
        354 => 'COValue',
        355 => 'TargetTemperatureType',
        356 => 'SetBackMode',
        357 => 'SystemAlarm',
        358 => 'HealthAlarm',
        359 => 'AccessControlAlarm',
        360 => 'SecurityAlarm',
        361 => 'EmergencyAlarm',
        362 => 'ClockAlarm',
        363 => 'ApplianceAlarm',
        364 => 'WaterValveAlarm',
        365 => 'WeatherAlarm',
        366 => 'IrrigationAlarm',
        367 => 'GasAlarm',
        368 => 'PestAlarm',
        369 => 'LightAlarm',
        370 => 'WaterQualityAlarm',
        371 => 'AntiTheftRestricted',
        372 => 'UnknownMeteringValue',
        373 => 'ColorExpert',
        375 => 'SwitchMultilevelExpert',
        376 => 'UnknownSensorValue',
        377 => 'DoorLockExpert',
        352 => 'VOCLevel',
        353 => 'VOCValue',
        378 => 'VentilateImpulse',
        379 => 'VibrationOnOff',
        380 => 'SoundOnOff',
        381 => 'VirtualVolantPostion',
        382 => 'FabricUntensioning',
        383 => 'AutomaticReversing',
        384 => 'Locked',
        385 => 'WatchdogOnOff',
        386 => 'IPAddress',
        387 => 'GasAlarmState',
        388 => 'GasConcentration',
        389 => 'Hostname',
        390 => 'BrightnessLevel',
        391 => 'ForecastLocalHumidity',
        392 => 'ForecastLocalWindSpeed',
        393 => 'ForecastLocalGustSpeed',
    ];
}
