<?php /** @noinspection PhpUnused */

declare(strict_types=1);

namespace HomeeApi\CA;

class CANodeProfile extends CA
{
    public const CANodeProfileNone = 0;
    public const CANodeProfileHomee = 1;
    public const CANodeProfileOnOffPlug = 10;
    public const CANodeProfileDimmableMeteringSwitch = 11;
    public const CANodeProfileMeteringSwitch = 12;
    public const CANodeProfileMeteringPlug = 13;
    public const CANodeProfileDimmablePlug = 14;
    public const CANodeProfileDimmableSwitch = 15;
    public const CANodeProfileOnOffSwitch = 16;
    public const CANodeProfileDoubleOnOffSwitch = 18;
    public const CANodeProfileDimmableMeteringPlug = 19;
    public const CANodeProfileOneButtonRemote = 20;
    public const CANodeProfileBinaryInput = 21;
    public const CANodeProfileDimmableColorMeteringPlug = 22;
    public const CANodeProfileDoubleBinaryInput = 23;
    public const CANodeProfileTwoButtonRemote = 24;
    public const CANodeProfileThreeButtonRemote = 25;
    public const CANodeProfileFourButtonRemote = 26;
    public const CANodeProfileAlarmSensor = 27;
    public const CANodeProfileDoubleOnOffPlug = 28;
    public const CANodeProfileOnOffSwitchWithBinaryInput = 29;
    public const CANodeProfileWatchDogWithPressureAndTemperatures = 30;
    public const CANodeProfileFibaroButton = 31;
    public const CANodeProfileEnergyMeter = 32;
    public const CANodeProfileDoubleMeteringSwitch = 33;
    public const CANodeProfileFibaroSwipe = 34;
    public const CANodeProfileEnergyManager = 38;
    public const CANodeProfileLevelMeter = 39;
    public const CANodeProfileRangeExtender = 40;
    public const CANodeProfileRemote = 41;
    public const CANodeProfileImpulsePlug = 42;
    public const CANodeProfileImpulseRelay = 43;
    public const CANodeProfileWallMote = 44;
    public const CANodeProfileWifiOneButtonRemote = 45;
    public const CANodeProfileWifiMeteringSwitch = 46;
    public const CANodeProfileWifiOnOffMeteringSwitch = 47;
    public const CANodeProfileWifiOnOffMeteringPlug = 48;
    public const CANodeProfileWifiOnOffDimmableMeteringSwitch = 49;
    public const CANodeProfileWifiOnOffSwitch = 50;
    public const CANodeProfileWifiEnergyMeter = 51;
    public const CANodeProfileBrightnessSensor = '1e3';
    public const CANodeProfileDimmableColorLight = 1001;
    public const CANodeProfileDimmableExtendedColorLight = 1002;
    public const CANodeProfileDimmableColorTemperatureLight = 1003;
    public const CANodeProfileDimmableLight = 1004;
    public const CANodeProfileDimmableLightWithBrightnessSensor = 1005;
    public const CANodeProfileDimmableLightWithBrightnessAndPresenceSensor = 1006;
    public const CANodeProfileDimmableLightWithPresenceSensor = 1007;
    public const CANodeProfileDimmableRGBWLight = 1008;
    public const CANodeProfileWifiDimmableRGBWLight = 1009;
    public const CANodeProfileWifiDimmableLight = 1010;
    public const CANodeProfileOpenCloseSensor = '2e3';
    public const CANodeProfileWindowHandle = 2001;
    public const CANodeProfileShutterPositionSwitch = 2002;
    public const CANodeProfileOpenCloseAndTemperatureSensor = 2003;
    public const CANodeProfileElectricMotorMeteringSwitch = 2004;
    public const CANodeProfileOpenCloseWithTemperatureAndBrightnessSensor = 2005;
    public const CANodeProfileElectricMotorMeteringSwitchWithoutSlatPosition = 2006;
    public const CANodeProfileLock = 2007;
    public const CANodeProfileWindowHandleWithButtons = 2008;
    public const CANodeProfileWindowHandleWithButtonsAndTemperatureAndHumiditySensor = 2009;
    public const CANodeProfileEntranceGateOperator = 2010;
    public const CANodeProfilePerimeterProtectionSystem = 2011;
    public const CANodeProfileGarageDoorOperator = 2012;
    public const CANodeProfileGateOperator = 2013;
    public const CANodeProfileInnerDoorOperator = 2014;
    public const CANodeProfileGarageDoorImpulseOperator = 2015;
    public const CANodeProfileEntranceDoor = 2016;
    public const CANodeProfileWindowMotorSwitch = 2017;
    public const CANodeProfileWifiOpenCloseSensor = 2018;
    public const CANodeProfileWifiElctricMotorMeteringSwitch = 2019;
    public const CANodeProfileTemperatureAndHumiditySensor = 3001;
    public const CANodeProfileCO2Sensor = 3002;
    public const CANodeProfileRoomThermostat = 3003;
    public const CANodeProfileRoomThermostatWithHumiditySensor = 3004;
    public const CANodeProfileBinaryInputWithTemperatureSensor = 3005;
    public const CANodeProfileRadiatorThermostat = 3006;
    public const CANodeProfileTemperatureSensor = 3009;
    public const CANodeProfileHumiditySensor = 3010;
    public const CANodeProfileWaterValve = 3011;
    public const CANodeProfileWaterMeter = 3012;
    public const CANodeProfileWeatherStation = 3013;
    public const CANodeProfileNetatmoMainModule = 3014;
    public const CANodeProfileNetatmoOutdoorModule = 3015;
    public const CANodeProfileNetatmoIndoorModule = 3016;
    public const CANodeProfileNetatmoRainModule = 3017;
    public const CANodeProfileCosiThermChannel = 3018;
    public const CANodeProfileVentilationControl = 3019;
    public const CANodeProfileThermostatWithHeatingAndCooling = 3022;
    public const CANodeProfileNetatmoWindModule = 3023;
    public const CANodeProfileElectricalHeating = 3024;
    public const CANodeProfileValveDrive = 3025;
    public const CANodeProfileCamera = 3026;
    public const CANodeProfileCameraWithFloodlight = 3027;
    public const CANodeProfileHeatingSystem = 3028;
    public const CANodeProfileWarmWaterCircuit = 3029;
    public const CANodeProfileHeatingCircuit = 3030;
    public const CANodeProfileAirQualitySensor = 3031;
    public const CANodeProfileWifiRoomThermostat = 3032;
    public const CANodeProfileWifiRadiatorThermostat = 3033;
    public const CANodeProfileMotionDetectorWithTemperatureBrightnessAndHumiditySensor = 4010;
    public const CANodeProfileMotionDetector = 4011;
    public const CANodeProfileSmokeDetector = 4012;
    public const CANodeProfileFloodDetector = 4013;
    public const CANodeProfilePresenceDetector = 4014;
    public const CANodeProfileMotionDetectorWithTemperatureAndBrightnessSensor = 4015;
    public const CANodeProfileSmokeDetectorWithTemperatureSensor = 4016;
    public const CANodeProfileFloodDetectorWithTemperatureSensor = 4017;
    public const CANodeProfileWatchDogDevice = 4018;
    public const CANodeProfileLAG = 4019;
    public const CANodeProfileOWU = 4020;
    public const CANodeProfileEurovac = 4021;
    public const CANodeProfileOWWG3 = 4022;
    public const CANodeProfileEuropress = 4023;
    public const CANodeProfileMinimumDetector = 4024;
    public const CANodeProfileMaximumDetector = 4025;
    public const CANodeProfileSmokeDetectorAndCODetector = 4026;
    public const CANodeProfileSiren = 4027;
    public const CANodeProfileMotionDetectorWithOpenCloseTemperatureAndBrightnessSensor = 4028;
    public const CANodeProfileMotionDetectorWithBrightness = 4029;
    public const CANodeProfileDoorbell = 4030;
    public const CANodeProfileSmokeDetectorAndSiren = 4031;
    public const CANodeProfileFloodDetectorWithTemperatureAndHumiditySensor = 4032;
    public const CANodeProfileMinimumDetectorWithTemperatureSensor = 4033;
    public const CANodeProfileMaximumDetectorWithTemperatureSensor = 4034;
    public const CANodeProfilePresenceDetectorWithTemperatureAndBrightnessSensor = 4035;
    public const CANodeProfileCODetector = 4036;
    public const CANodeProfileTracker = 4037;
    public const CANodeProfileWifiFloodDetector = 4038;
    public const CANodeProfileWifiMotionDetector = 4039;
    public const CANodeProfileWifiGasDetector = 4040;
    public const CANodeProfileInovaAlarmSystem = '5e3';
    public const CANodeProfileInovaDetector = 5001;
    public const CANodeProfileInovaSiren = 5002;
    public const CANodeProfileInovaCommand = 5003;
    public const CANodeProfileInovaTransmitter = 5004;
    public const CANodeProfileInovaReciever = 5005;
    public const CANodeProfileInovaKoala = 5006;
    public const CANodeProfileInovaInternalTransmitter = 5007;
    public const CANodeProfileInovaControlPanel = 5008;
    public const CANodeProfileInovaInputOutputExtension = 5009;
    public const CANodeProfileInovaMotionDetectorWithVOD = 5010;
    public const CANodeProfileInovaMotionDetector = 5011;
    public const CANodeProfileWashingMachine = '6e3';
    public const CANodeProfileTumbleDryer = 6001;
    public const CANodeProfileDishwasher = 6002;

    protected static array $mapping = [
        0 => 'None',
        1 => 'Homee',
        10 => 'OnOffPlug',
        11 => 'DimmableMeteringSwitch',
        12 => 'MeteringSwitch',
        13 => 'MeteringPlug',
        14 => 'DimmablePlug',
        15 => 'DimmableSwitch',
        16 => 'OnOffSwitch',
        18 => 'DoubleOnOffSwitch',
        19 => 'DimmableMeteringPlug',
        20 => 'OneButtonRemote',
        21 => 'BinaryInput',
        22 => 'DimmableColorMeteringPlug',
        23 => 'DoubleBinaryInput',
        24 => 'TwoButtonRemote',
        25 => 'ThreeButtonRemote',
        26 => 'FourButtonRemote',
        27 => 'AlarmSensor',
        28 => 'DoubleOnOffPlug',
        29 => 'OnOffSwitchWithBinaryInput',
        30 => 'WatchDogWithPressureAndTemperatures',
        31 => 'FibaroButton',
        32 => 'EnergyMeter',
        33 => 'DoubleMeteringSwitch',
        34 => 'FibaroSwipe',
        38 => 'EnergyManager',
        39 => 'LevelMeter',
        40 => 'RangeExtender',
        41 => 'Remote',
        42 => 'ImpulsePlug',
        43 => 'ImpulseRelay',
        44 => 'WallMote',
        45 => 'WifiOneButtonRemote',
        46 => 'WifiMeteringSwitch',
        47 => 'WifiOnOffMeteringSwitch',
        48 => 'WifiOnOffMeteringPlug',
        49 => 'WifiOnOffDimmableMeteringSwitch',
        50 => 'WifiOnOffSwitch',
        51 => 'WifiEnergyMeter',
        '1e3' => 'BrightnessSensor',
        1001 => 'DimmableColorLight',
        1002 => 'DimmableExtendedColorLight',
        1003 => 'DimmableColorTemperatureLight',
        1004 => 'DimmableLight',
        1005 => 'DimmableLightWithBrightnessSensor',
        1006 => 'DimmableLightWithBrightnessAndPresenceSensor',
        1007 => 'DimmableLightWithPresenceSensor',
        1008 => 'DimmableRGBWLight',
        1009 => 'WifiDimmableRGBWLight',
        1010 => 'WifiDimmableLight',
        '2e3' => 'OpenCloseSensor',
        2001 => 'WindowHandle',
        2002 => 'ShutterPositionSwitch',
        2003 => 'OpenCloseAndTemperatureSensor',
        2004 => 'ElectricMotorMeteringSwitch',
        2005 => 'OpenCloseWithTemperatureAndBrightnessSensor',
        2006 => 'ElectricMotorMeteringSwitchWithoutSlatPosition',
        2007 => 'Lock',
        2008 => 'WindowHandleWithButtons',
        2009 => 'WindowHandleWithButtonsAndTemperatureAndHumiditySensor',
        2010 => 'EntranceGateOperator',
        2011 => 'PerimeterProtectionSystem',
        2012 => 'GarageDoorOperator',
        2013 => 'GateOperator',
        2014 => 'InnerDoorOperator',
        2015 => 'GarageDoorImpulseOperator',
        2016 => 'EntranceDoor',
        2017 => 'WindowMotorSwitch',
        2018 => 'WifiOpenCloseSensor',
        2019 => 'WifiElctricMotorMeteringSwitch',
        3001 => 'TemperatureAndHumiditySensor',
        3002 => 'CO2Sensor',
        3003 => 'RoomThermostat',
        3004 => 'RoomThermostatWithHumiditySensor',
        3005 => 'BinaryInputWithTemperatureSensor',
        3006 => 'RadiatorThermostat',
        3009 => 'TemperatureSensor',
        3010 => 'HumiditySensor',
        3011 => 'WaterValve',
        3012 => 'WaterMeter',
        3013 => 'WeatherStation',
        3014 => 'NetatmoMainModule',
        3015 => 'NetatmoOutdoorModule',
        3016 => 'NetatmoIndoorModule',
        3017 => 'NetatmoRainModule',
        3018 => 'CosiThermChannel',
        3019 => 'VentilationControl',
        3022 => 'ThermostatWithHeatingAndCooling',
        3023 => 'NetatmoWindModule',
        3024 => 'ElectricalHeating',
        3025 => 'ValveDrive',
        3026 => 'Camera',
        3027 => 'CameraWithFloodlight',
        3028 => 'HeatingSystem',
        3029 => 'WarmWaterCircuit',
        3030 => 'HeatingCircuit',
        3031 => 'AirQualitySensor',
        3032 => 'WifiRoomThermostat',
        3033 => 'WifiRadiatorThermostat',
        4010 => 'MotionDetectorWithTemperatureBrightnessAndHumiditySensor',
        4011 => 'MotionDetector',
        4012 => 'SmokeDetector',
        4013 => 'FloodDetector',
        4014 => 'PresenceDetector',
        4015 => 'MotionDetectorWithTemperatureAndBrightnessSensor',
        4016 => 'SmokeDetectorWithTemperatureSensor',
        4017 => 'FloodDetectorWithTemperatureSensor',
        4018 => 'WatchDogDevice',
        4019 => 'LAG',
        4020 => 'OWU',
        4021 => 'Eurovac',
        4022 => 'OWWG3',
        4023 => 'Europress',
        4024 => 'MinimumDetector',
        4025 => 'MaximumDetector',
        4026 => 'SmokeDetectorAndCODetector',
        4027 => 'Siren',
        4028 => 'MotionDetectorWithOpenCloseTemperatureAndBrightnessSensor',
        4029 => 'MotionDetectorWithBrightness',
        4030 => 'Doorbell',
        4031 => 'SmokeDetectorAndSiren',
        4032 => 'FloodDetectorWithTemperatureAndHumiditySensor',
        4033 => 'MinimumDetectorWithTemperatureSensor',
        4034 => 'MaximumDetectorWithTemperatureSensor',
        4035 => 'PresenceDetectorWithTemperatureAndBrightnessSensor',
        4036 => 'CODetector',
        4037 => 'Tracker',
        4038 => 'WifiFloodDetector',
        4039 => 'WifiMotionDetector',
        4040 => 'WifiGasDetector',
        '5e3' => 'InovaAlarmSystem',
        5001 => 'InovaDetector',
        5002 => 'InovaSiren',
        5003 => 'InovaCommand',
        5004 => 'InovaTransmitter',
        5005 => 'InovaReciever',
        5006 => 'InovaKoala',
        5007 => 'InovaInternalTransmitter',
        5008 => 'InovaControlPanel',
        5009 => 'InovaInputOutputExtension',
        5010 => 'InovaMotionDetectorWithVOD',
        5011 => 'InovaMotionDetector',
        '6e3' => 'WashingMachine',
        6001 => 'TumbleDryer',
        600 => 'Dishwasher',
    ];
}
